# Generated by Django 2.0.6 on 2018-06-03 12:35

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('post_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('posted_by_email', models.EmailField(max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('job_title', models.TextField(max_length=30)),
                ('job_description', models.TextField(max_length=500)),
                ('job_location', models.TextField(max_length=20)),
                ('job_type', models.TextField(max_length=10, null=True)),
                ('job_skills', models.TextField(max_length=10, null=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('post_id', models.IntegerField()),
                ('apply_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.TextField(max_length=20)),
                ('user_full_name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=50)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('gender', models.TextField(max_length=1)),
                ('is_active', models.TextField(max_length=1)),
                ('contact_number', models.IntegerField(default=None, null=True)),
                ('sms_notification_active', models.TextField(max_length=1)),
                ('email_notification_active', models.TextField(max_length=1)),
                ('user_image', models.FileField(upload_to=portal.models.user_directory_path)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('activation_code', models.TextField(default=None, max_length=50, null=True)),
                ('account_activated', models.TextField(default=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_acc_id', models.IntegerField()),
                ('last_login_date', models.DateField(auto_now_add=True)),
                ('last_job_apply', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.TextField(max_length=20)),
            ],
        ),
    ]
