# Generated by Django 2.0.6 on 2018-06-04 09:52

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_image',
            field=models.ImageField(upload_to=portal.models.user_directory_path),
        ),
    ]
