# Generated by Django 2.0.6 on 2018-06-04 11:17

from django.db import migrations, models
import django.utils.timezone
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180604_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to=portal.models.user_directory_path),
            preserve_default=False,
        ),
    ]
